javafamily:
   notify:
      feishu:
         hook-url: https://open.feishu.cn/open-apis/bot/v2/hook/31a65e6b-0dab-491c-8de9-df3d16c19050
         security-type: keyword
         keyWord: 测试

      dingtalk:
         hook-url: https://oapi.dingtalk.com/robot/send?access_token=5221404563667b04140f92e5820e6213fcdc2fe6a97560fe1f233fd468ef8e75
         security-type: keyword
         keyWord: 测试

      sms:
         tencent:
            #  请填写自己的短信平台信息, 这些信息已经过时
            sdkAppId: 1234567899
            secretId: LVqiEb4kuLVqiEbl4JAg5xosFnL
            secretKey: SRK4u5zMcLXjp6eDKJyuWYmF26SRKDKJyLi1DY3Ur
            sign: JavaFamily
            config: {
               default: {
                  templateId: 1111111,
                  receive-users: ['+86136xxxxxxxx', 188xxxxxxxx]
               }
            }

         ucloud:
            publicKey: LVqqiEb4kuaLVqiEbl4JAg5xosFnL
            privateKey: SRKq4u5zaMcLXjp6eDKJyuWYmF26SRKDKJyLi1DY3Ur
            projectId: org-javafamily1
            sign: JavaFamily1
            config: {
               default: {
                  templateId: UTA2111111111111,
                  receive-users: ['+86136xxxxyyyy', 188xxxxxxxx]
               }
            }

